import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(packageRoot, "../..");
const specRoot = path.join(repoRoot, "spec");
const schemaRoot = path.join(specRoot, "schemas");
const catalogRoot = path.join(specRoot, "catalogs");
const generatedRoot = path.join(packageRoot, "src", "generated");
const generatedTypesRoot = path.join(generatedRoot, "types");

const schemaDefinitions = [
  { name: "presentation", typeName: "Presentation", file: "opf.schema.json" },
  { name: "audience", typeName: "Audience", file: "audience.schema.json" },
  { name: "purpose", typeName: "Purpose", file: "purpose.schema.json" },
  { name: "tone", typeName: "Tone", file: "tone.schema.json" },
  { name: "theme", typeName: "Theme", file: "theme.schema.json" },
  { name: "layout", typeName: "Layout", file: "layout.schema.json" },
  { name: "chartType", typeName: "ChartType", file: "chart-type.schema.json", typeFile: "chart-type" },
  { name: "narrative", typeName: "Narrative", file: "narrative.schema.json" },
  { name: "socialPlatform", typeName: "SocialPlatform", file: "social-platform.schema.json", typeFile: "social-platform" },
  { name: "language", typeName: "Language", file: "language.schema.json" },
  { name: "colorScheme", typeName: "ColorScheme", file: "color-scheme.schema.json", typeFile: "color-scheme" },
  { name: "fontScheme", typeName: "FontScheme", file: "font-scheme.schema.json", typeFile: "font-scheme" },
];

const catalogDefinitions = [
  { kind: "audiences", schemaName: "audience", dir: "audiences" },
  { kind: "purposes", schemaName: "purpose", dir: "purposes" },
  { kind: "tones", schemaName: "tone", dir: "tones" },
  { kind: "themes", schemaName: "theme", dir: "themes" },
  { kind: "layouts", schemaName: "layout", dir: "layouts" },
  { kind: "chartTypes", schemaName: "chartType", dir: "chart-types" },
  { kind: "narratives", schemaName: "narrative", dir: "narratives", indexRecordsKey: "templates" },
  { kind: "socialPlatforms", schemaName: "socialPlatform", dir: "social-platforms" },
  { kind: "languages", schemaName: "language", dir: "languages" },
  { kind: "colorSchemes", schemaName: "colorScheme", dir: "color-schemes" },
  { kind: "fontSchemes", schemaName: "fontScheme", dir: "font-schemes" },
];

async function readJson(file) {
  return JSON.parse(await fs.readFile(file, "utf8"));
}

function generatedHeader(source) {
  return `// Generated by scripts/generate.mjs from ${source}. Do not edit by hand.\n\n`;
}

function asTs(value) {
  return JSON.stringify(value, null, 2);
}

async function collectFiles(root, dir = root) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolutePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectFiles(root, absolutePath));
    } else if (entry.isFile()) {
      files.push(path.relative(root, absolutePath).split(path.sep).join(path.posix.sep));
    }
  }
  return files.sort();
}

function specFileKind(file) {
  if (file === "openapi.yaml") {
    return "openapi";
  }
  if (file.startsWith("schemas/")) {
    return "schema";
  }
  if (file.startsWith("catalogs/") && file.endsWith("/index.json")) {
    return "catalogIndex";
  }
  if (file.startsWith("catalogs/")) {
    return "catalogRecord";
  }
  if (file.startsWith("reference/")) {
    return "reference";
  }
  return "spec";
}

function mediaTypeForSpecFile(file) {
  if (file.endsWith(".json")) {
    return "application/json";
  }
  if (file.endsWith(".yaml") || file.endsWith(".yml")) {
    return "application/yaml";
  }
  return "application/octet-stream";
}

async function generateSchemas() {
  const schemas = [];
  for (const definition of schemaDefinitions) {
    schemas.push({ ...definition, schema: await readJson(path.join(schemaRoot, definition.file)) });
  }

  const lines = [generatedHeader("spec/schemas/*.schema.json"), 'import type { JsonSchema } from "../json.js";', ""];
  for (const { name, schema } of schemas) {
    lines.push(`export const ${name} = ${asTs(schema)} as const satisfies JsonSchema;`, "");
  }
  lines.push("export const schemas = {");
  for (const { name } of schemas) {
    lines.push(`  ${name},`);
  }
  lines.push("} as const;", "");
  lines.push(`export const schemaNames = ${asTs(schemas.map(({ name }) => name))} as const;`, "");
  lines.push("export const schemaEntries = [");
  for (const { name, file } of schemas) {
    lines.push(`  { name: ${JSON.stringify(name)}, file: ${JSON.stringify(path.posix.join("schemas", file))}, schema: ${name} },`);
  }
  lines.push("] as const;", "");
  lines.push("export type SchemaName = keyof typeof schemas;", "");

  await fs.writeFile(path.join(generatedRoot, "schemas.ts"), lines.join("\n"));
}

async function orderedCatalogFiles(definition, catalogDir, index) {
  const key = definition.indexRecordsKey ?? "records";
  const indexedFiles = Array.isArray(index[key])
    ? index[key].map((record) => record.file).filter(Boolean)
    : [];
  const allFiles = (await fs.readdir(catalogDir))
    .filter((file) => file.endsWith(".json") && file !== "index.json")
    .sort();
  const extras = allFiles.filter((file) => !indexedFiles.includes(file));
  return [...indexedFiles, ...extras];
}

async function generateCatalogs() {
  const catalogs = [];
  for (const definition of catalogDefinitions) {
    const catalogDir = path.join(catalogRoot, definition.dir);
    const index = await readJson(path.join(catalogDir, "index.json"));
    const files = await orderedCatalogFiles(definition, catalogDir, index);
    const records = [];
    for (const file of files) {
      records.push(await readJson(path.join(catalogDir, file)));
    }
    catalogs.push({ ...definition, index, records, files });
  }

  const lines = [generatedHeader("spec/catalogs/<catalog-kind>/*.json")];
  for (const { kind, records } of catalogs) {
    lines.push(`export const ${kind} = ${asTs(records)} as const;`, "");
  }
  lines.push("export const catalogs = {");
  for (const { kind } of catalogs) {
    lines.push(`  ${kind},`);
  }
  lines.push("} as const;", "");
  lines.push("export const catalogIndexes = {");
  for (const { kind, index } of catalogs) {
    lines.push(`  ${kind}: ${asTs(index)},`);
  }
  lines.push("} as const;", "");
  lines.push("export const catalogSchemaNames = {");
  for (const { kind, schemaName } of catalogs) {
    lines.push(`  ${kind}: ${JSON.stringify(schemaName)},`);
  }
  lines.push("} as const;", "");
  lines.push(`export const catalogKinds = ${asTs(catalogs.map(({ kind }) => kind))} as const;`, "");
  lines.push("export const catalogEntries = [");
  for (const { kind, schemaName, dir, files } of catalogs) {
    const specDir = path.posix.join("catalogs", dir);
    lines.push(
      `  { kind: ${JSON.stringify(kind)}, schemaName: ${JSON.stringify(schemaName)}, dir: ${JSON.stringify(specDir)}, files: ${asTs(files)}, records: ${kind}, index: catalogIndexes.${kind} },`,
    );
  }
  lines.push("] as const;", "");
  lines.push("export type CatalogKind = keyof typeof catalogs;", "");

  await fs.writeFile(path.join(generatedRoot, "catalogs.ts"), lines.join("\n"));
}

async function generateSpecFiles() {
  const files = await collectFiles(specRoot);
  const entries = files.map((file) => ({
    path: file,
    packagePath: `@openpresentation/opf/spec/${file}`,
    kind: specFileKind(file),
    mediaType: mediaTypeForSpecFile(file),
  }));
  const kinds = [...new Set(entries.map((entry) => entry.kind))];

  const lines = [generatedHeader("spec/**/*")];
  lines.push(`export const specFileEntries = ${asTs(entries)} as const;`, "");
  lines.push(`export const specFilePaths = ${asTs(files)} as const;`, "");
  lines.push(`export const specFileKinds = ${asTs(kinds)} as const;`, "");
  lines.push("export type SpecFileEntry = typeof specFileEntries[number];", "");
  lines.push("export type SpecFilePath = typeof specFilePaths[number];", "");
  lines.push("export type SpecFileKind = typeof specFileKinds[number];", "");

  await fs.writeFile(path.join(generatedRoot, "spec-files.ts"), lines.join("\n"));
}

async function generateTypes() {
  await fs.mkdir(generatedTypesRoot, { recursive: true });
  for (const definition of schemaDefinitions) {
    const schema = await readJson(path.join(schemaRoot, definition.file));
    const schemaForTypes = JSON.parse(JSON.stringify(schema));
    schemaForTypes.title = definition.typeName;
    const typeFile = definition.typeFile ?? definition.name;
    const source = await compile(schemaForTypes, definition.typeName, {
      bannerComment: generatedHeader(path.posix.join("schemas", definition.file)).trimEnd(),
      unreachableDefinitions: true,
      format: false,
      style: {
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "all",
      },
    });
    await fs.writeFile(path.join(generatedTypesRoot, `${typeFile}.ts`), source);
  }
}

await fs.rm(generatedRoot, { recursive: true, force: true });
await fs.mkdir(generatedRoot, { recursive: true });
await generateSchemas();
await generateCatalogs();
await generateSpecFiles();
await generateTypes();
