import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(packageRoot, "../..");
const specRoot = path.join(repoRoot, "spec");
const generatedRoot = path.join(packageRoot, "src", "generated");
const generatedTypesRoot = path.join(generatedRoot, "types");

const schemaDefinitions = [
  { name: "presentation", typeName: "Presentation", file: "presentation.schema.json" },
  { name: "audience", typeName: "Audience", file: "audience.schema.json" },
  { name: "tone", typeName: "Tone", file: "tone.schema.json" },
  { name: "theme", typeName: "Theme", file: "theme.schema.json" },
  { name: "layout", typeName: "Layout", file: "layout.schema.json" },
  { name: "chart", typeName: "Chart", file: "chart.schema.json" },
  { name: "narrative", typeName: "Narrative", file: "narrative.schema.json" },
  { name: "social", typeName: "Social", file: "social.schema.json" },
  { name: "language", typeName: "Language", file: "language.schema.json" },
  { name: "colorScheme", typeName: "ColorScheme", file: "color-scheme.schema.json", typeFile: "color-scheme" },
  { name: "fontScheme", typeName: "FontScheme", file: "font-scheme.schema.json", typeFile: "font-scheme" },
];

const catalogDefinitions = [
  { kind: "audiences", schemaName: "audience", dir: "audiences" },
  { kind: "tones", schemaName: "tone", dir: "tones" },
  { kind: "themes", schemaName: "theme", dir: "themes" },
  { kind: "layouts", schemaName: "layout", dir: "layouts" },
  { kind: "charts", schemaName: "chart", dir: "charts" },
  { kind: "narratives", schemaName: "narrative", dir: "narratives", indexRecordsKey: "templates" },
  { kind: "socials", schemaName: "social", dir: "socials" },
  { kind: "languages", schemaName: "language", dir: "languages" },
  { kind: "colorSchemes", schemaName: "colorScheme", dir: "color-schemes" },
  { kind: "fontSchemes", schemaName: "fontScheme", dir: "font-schemes" },
];

async function readJson(file) {
  return JSON.parse(await fs.readFile(file, "utf8"));
}

function generatedHeader(source) {
  return `// Generated by scripts/generate.mjs from ${source}. Do not edit by hand.\n\n`;
}

function asTs(value) {
  return JSON.stringify(value, null, 2);
}

async function generateSchemas() {
  const schemas = [];
  for (const definition of schemaDefinitions) {
    schemas.push({ ...definition, schema: await readJson(path.join(specRoot, definition.file)) });
  }

  const lines = [generatedHeader("spec/*.schema.json"), 'import type { JsonSchema } from "../json.js";', ""];
  for (const { name, schema } of schemas) {
    lines.push(`export const ${name} = ${asTs(schema)} as const satisfies JsonSchema;`, "");
  }
  lines.push("export const schemas = {");
  for (const { name } of schemas) {
    lines.push(`  ${name},`);
  }
  lines.push("} as const;", "");
  lines.push(`export const schemaNames = ${asTs(schemas.map(({ name }) => name))} as const;`, "");
  lines.push("export const schemaEntries = [");
  for (const { name, file } of schemas) {
    lines.push(`  { name: ${JSON.stringify(name)}, file: ${JSON.stringify(file)}, schema: ${name} },`);
  }
  lines.push("] as const;", "");
  lines.push("export type SchemaName = keyof typeof schemas;", "");

  await fs.writeFile(path.join(generatedRoot, "schemas.ts"), lines.join("\n"));
}

async function orderedCatalogFiles(definition, catalogDir, index) {
  const key = definition.indexRecordsKey ?? "records";
  const indexedFiles = Array.isArray(index[key])
    ? index[key].map((record) => record.file).filter(Boolean)
    : [];
  const allFiles = (await fs.readdir(catalogDir))
    .filter((file) => file.endsWith(".json") && file !== "index.json")
    .sort();
  const extras = allFiles.filter((file) => !indexedFiles.includes(file));
  return [...indexedFiles, ...extras];
}

async function generateCatalogs() {
  const catalogs = [];
  for (const definition of catalogDefinitions) {
    const catalogDir = path.join(specRoot, definition.dir);
    const index = await readJson(path.join(catalogDir, "index.json"));
    const files = await orderedCatalogFiles(definition, catalogDir, index);
    const records = [];
    for (const file of files) {
      records.push(await readJson(path.join(catalogDir, file)));
    }
    catalogs.push({ ...definition, index, records, files });
  }

  const lines = [generatedHeader("spec/<catalog-kind>/*.json")];
  for (const { kind, records } of catalogs) {
    lines.push(`export const ${kind} = ${asTs(records)} as const;`, "");
  }
  lines.push("export const catalogs = {");
  for (const { kind } of catalogs) {
    lines.push(`  ${kind},`);
  }
  lines.push("} as const;", "");
  lines.push("export const catalogIndexes = {");
  for (const { kind, index } of catalogs) {
    lines.push(`  ${kind}: ${asTs(index)},`);
  }
  lines.push("} as const;", "");
  lines.push("export const catalogSchemaNames = {");
  for (const { kind, schemaName } of catalogs) {
    lines.push(`  ${kind}: ${JSON.stringify(schemaName)},`);
  }
  lines.push("} as const;", "");
  lines.push(`export const catalogKinds = ${asTs(catalogs.map(({ kind }) => kind))} as const;`, "");
  lines.push("export const catalogEntries = [");
  for (const { kind, schemaName, dir, files } of catalogs) {
    lines.push(
      `  { kind: ${JSON.stringify(kind)}, schemaName: ${JSON.stringify(schemaName)}, dir: ${JSON.stringify(dir)}, files: ${asTs(files)}, records: ${kind}, index: catalogIndexes.${kind} },`,
    );
  }
  lines.push("] as const;", "");
  lines.push("export type CatalogKind = keyof typeof catalogs;", "");

  await fs.writeFile(path.join(generatedRoot, "catalogs.ts"), lines.join("\n"));
}

async function generateTypes() {
  await fs.mkdir(generatedTypesRoot, { recursive: true });
  for (const definition of schemaDefinitions) {
    const schema = await readJson(path.join(specRoot, definition.file));
    const schemaForTypes = JSON.parse(JSON.stringify(schema));
    schemaForTypes.title = definition.typeName;
    const typeFile = definition.typeFile ?? definition.name;
    const source = await compile(schemaForTypes, definition.typeName, {
      bannerComment: generatedHeader(definition.file).trimEnd(),
      unreachableDefinitions: true,
      format: false,
      style: {
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "all",
      },
    });
    await fs.writeFile(path.join(generatedTypesRoot, `${typeFile}.ts`), source);
  }
}

await fs.rm(generatedRoot, { recursive: true, force: true });
await fs.mkdir(generatedRoot, { recursive: true });
await generateSchemas();
await generateCatalogs();
await generateTypes();
