// Builds src/generated/{examples,docs,repo-readme}.ts by inlining the example
// .opf.json decks, the top-level docs/*.md files, and the repo README.md.
//
// Source-of-truth lives at the repo root:
//   - examples/**/*.opf.json
//   - docs/*.md       (top-level only; subdirectories like docs/migrations and
//                      docs/plans are intentionally excluded for now — they
//                      change too often to ship inside a pinned npm release)
//   - README.md
//
// Run via `pnpm generate` (wired in package.json after the schema/catalog gen).

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(packageRoot, "../..");
const examplesRoot = path.join(repoRoot, "examples");
const docsRoot = path.join(repoRoot, "docs");
const readmePath = path.join(repoRoot, "README.md");
const generatedRoot = path.join(packageRoot, "src/generated");

await fs.mkdir(generatedRoot, { recursive: true });

function generatedHeader(source) {
  return `// Generated by scripts/generate-content.mjs from ${source}. Do not edit by hand.\n\n`;
}

function posix(relPath) {
  return relPath.split(path.sep).join(path.posix.sep);
}

async function collectFiles(root, predicate) {
  const out = [];
  async function walk(dir) {
    const entries = await fs.readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const abs = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(abs);
      } else if (entry.isFile()) {
        const rel = posix(path.relative(root, abs));
        if (predicate(rel, entry.name)) out.push(rel);
      }
    }
  }
  await walk(root);
  out.sort();
  return out;
}

function exampleCategory(relativeFromExamples) {
  const segments = relativeFromExamples.split("/");
  return segments[0] ?? "";
}

function exampleGallerySlug(relativeFromExamples) {
  const segments = relativeFromExamples.split("/");
  if (segments[0] !== "gallery") return null;
  return segments[1] ?? null;
}

function exampleSlug(relativeFromExamples) {
  const base = path.posix.basename(relativeFromExamples);
  return base.replace(/\.opf\.json$/, "");
}

async function generateExamples() {
  const files = await collectFiles(examplesRoot, (rel) => rel.endsWith(".opf.json"));
  const examples = [];
  for (const file of files) {
    const json = JSON.parse(await fs.readFile(path.join(examplesRoot, file), "utf8"));
    examples.push({
      slug: exampleSlug(file),
      file: `examples/${file}`,
      category: exampleCategory(file),
      gallery: exampleGallerySlug(file),
      deck: json,
    });
  }

  const galleries = [];
  const galleryMap = new Map();
  for (const example of examples) {
    if (example.gallery === null) continue;
    if (!galleryMap.has(example.gallery)) {
      const slug = example.gallery;
      const entry = { slug, dir: `examples/gallery/${slug}`, examples: [] };
      galleryMap.set(slug, entry);
      galleries.push(entry);
    }
    galleryMap.get(example.gallery).examples.push({
      slug: example.slug,
      file: example.file,
      name: typeof example.deck?.name === "string" ? example.deck.name : null,
    });
  }
  galleries.sort((a, b) => a.slug.localeCompare(b.slug));

  const banner = generatedHeader("examples/**/*.opf.json");
  const exampleLiteral = JSON.stringify(examples, null, 2);
  const galleriesLiteral = JSON.stringify(galleries, null, 2);

  const source =
    banner +
    'import type { Presentation } from "../types.js";\n\n' +
    "export interface ExampleRecord {\n" +
    "  /** Filename slug, without the `.opf.json` suffix. */\n" +
    "  readonly slug: string;\n" +
    "  /** Path relative to the repo root, with forward slashes. */\n" +
    "  readonly file: string;\n" +
    "  /** Top-level examples/<category> bucket (`gallery`, `technical`, …). */\n" +
    "  readonly category: string;\n" +
    "  /** Gallery slug when the example lives under `examples/gallery/<slug>/`; otherwise `null`. */\n" +
    "  readonly gallery: string | null;\n" +
    "  /** Parsed OPF document. Validated against `presentation.schema.json` at build time. */\n" +
    "  readonly deck: Presentation;\n" +
    "}\n\n" +
    "export interface GalleryRecord {\n" +
    "  /** Gallery slug (folder name under `examples/gallery/`). */\n" +
    "  readonly slug: string;\n" +
    "  /** Directory path relative to the repo root. */\n" +
    "  readonly dir: string;\n" +
    "  /** Lightweight summary of every example deck inside the gallery. */\n" +
    "  readonly examples: readonly { readonly slug: string; readonly file: string; readonly name: string | null }[];\n" +
    "}\n\n" +
    `const examplesData: readonly ExampleRecord[] = Object.freeze(${exampleLiteral} as readonly ExampleRecord[]);\n\n` +
    `const galleriesData: readonly GalleryRecord[] = Object.freeze(${galleriesLiteral} as readonly GalleryRecord[]);\n\n` +
    "export const examplesRaw = examplesData;\n" +
    "export const galleriesRaw = galleriesData;\n";

  await fs.writeFile(path.join(generatedRoot, "examples.ts"), source, "utf8");
  console.log(`Generated src/generated/examples.ts (${examples.length} examples, ${galleries.length} galleries)`);
}

function extractFirstHeading(markdown) {
  const match = markdown.match(/^#\s+(.+?)\s*$/m);
  return match ? match[1].trim() : null;
}

function titleFromSlug(slug) {
  return slug.replace(/[-_]+/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

async function generateDocs() {
  // docs/*.md only — skip the BACKLOG and any subdirectory until we have a
  // separate policy for shipping migration/plan notes inside the package.
  const entries = await fs.readdir(docsRoot, { withFileTypes: true });
  const files = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".md") && entry.name !== "BACKLOG.md")
    .map((entry) => entry.name)
    .sort();

  const docs = [];
  for (const name of files) {
    const slug = name.replace(/\.md$/, "");
    const markdown = await fs.readFile(path.join(docsRoot, name), "utf8");
    docs.push({
      slug,
      file: `docs/${name}`,
      title: extractFirstHeading(markdown) ?? titleFromSlug(slug),
      markdown,
    });
  }

  const banner = generatedHeader("docs/*.md");
  const docsLiteral = JSON.stringify(docs, null, 2);
  const source =
    banner +
    "export interface DocRecord {\n" +
    "  /** Filename slug, without the `.md` suffix. */\n" +
    "  readonly slug: string;\n" +
    "  /** Path relative to the repo root, with forward slashes. */\n" +
    "  readonly file: string;\n" +
    "  /** First-level heading from the markdown, falling back to a slug-derived title. */\n" +
    "  readonly title: string;\n" +
    "  /** Raw markdown content. */\n" +
    "  readonly markdown: string;\n" +
    "}\n\n" +
    `const docsData: readonly DocRecord[] = Object.freeze(${docsLiteral} as readonly DocRecord[]);\n\n` +
    "export const docsRaw = docsData;\n";

  await fs.writeFile(path.join(generatedRoot, "docs.ts"), source, "utf8");
  console.log(`Generated src/generated/docs.ts (${docs.length} docs)`);
}

async function generateRepoReadme() {
  const markdown = await fs.readFile(readmePath, "utf8");
  const banner = generatedHeader("README.md");
  const literal = JSON.stringify(markdown);
  const source =
    banner +
    `export const repoReadmeRaw: string = ${literal};\n`;
  await fs.writeFile(path.join(generatedRoot, "repo-readme.ts"), source, "utf8");
  console.log(`Generated src/generated/repo-readme.ts (${markdown.length} bytes)`);
}

await generateExamples();
await generateDocs();
await generateRepoReadme();
