import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const repoRoot = path.resolve(packageRoot, "../..");
const specRoot = path.join(repoRoot, "spec");
const schemaRoot = path.join(specRoot, "schemas");
const catalogRoot = path.join(specRoot, "catalogs");
const generatedRoot = path.join(packageRoot, "src", "generated");
const generatedTypesRoot = path.join(generatedRoot, "types");

const schemaDefinitions = [
  { name: "presentation", typeName: "Presentation", file: "opf.schema.json" },
  { name: "audience", typeName: "Audience", file: "audience.schema.json" },
  { name: "purpose", typeName: "Purpose", file: "purpose.schema.json" },
  { name: "tone", typeName: "Tone", file: "tone.schema.json" },
  { name: "theme", typeName: "Theme", file: "theme.schema.json" },
  { name: "layout", typeName: "Layout", file: "layout.schema.json" },
  { name: "chartType", typeName: "ChartType", file: "chart-type.schema.json", typeFile: "chart-type" },
  { name: "narrative", typeName: "Narrative", file: "narrative.schema.json" },
  { name: "socialPlatform", typeName: "SocialPlatform", file: "social-platform.schema.json", typeFile: "social-platform" },
  { name: "language", typeName: "Language", file: "language.schema.json" },
  { name: "colorScheme", typeName: "ColorScheme", file: "color-scheme.schema.json", typeFile: "color-scheme" },
  { name: "fontScheme", typeName: "FontScheme", file: "font-scheme.schema.json", typeFile: "font-scheme" },
];

const catalogDefinitions = [
  { kind: "audiences", schemaName: "audience", dir: "audiences" },
  { kind: "purposes", schemaName: "purpose", dir: "purposes" },
  { kind: "tones", schemaName: "tone", dir: "tones" },
  { kind: "themes", schemaName: "theme", dir: "themes" },
  { kind: "layouts", schemaName: "layout", dir: "layouts" },
  { kind: "chartTypes", schemaName: "chartType", dir: "chart-types" },
  { kind: "narratives", schemaName: "narrative", dir: "narratives" },
  { kind: "socialPlatforms", schemaName: "socialPlatform", dir: "social-platforms" },
  { kind: "languages", schemaName: "language", dir: "languages" },
  { kind: "colorSchemes", schemaName: "colorScheme", dir: "color-schemes" },
  { kind: "fontSchemes", schemaName: "fontScheme", dir: "font-schemes" },
];

async function readJson(file) {
  return JSON.parse(await fs.readFile(file, "utf8"));
}

function generatedHeader(source) {
  return `// Generated by scripts/generate.mjs from ${source}. Do not edit by hand.\n\n`;
}

function asTs(value) {
  return JSON.stringify(value, null, 2);
}

async function collectFiles(root, dir = root) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const absolutePath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...await collectFiles(root, absolutePath));
    } else if (entry.isFile()) {
      files.push(path.relative(root, absolutePath).split(path.sep).join(path.posix.sep));
    }
  }
  return files.sort();
}

function specFileKind(file) {
  if (file === "openapi.yaml") {
    return "openapi";
  }
  if (file.startsWith("schemas/")) {
    return "schema";
  }
  if (file.startsWith("catalogs/") && file.endsWith("/index.json")) {
    return "catalogIndex";
  }
  if (file.startsWith("catalogs/")) {
    return "catalogRecord";
  }
  if (file.startsWith("reference/")) {
    return "reference";
  }
  return "spec";
}

function mediaTypeForSpecFile(file) {
  if (file.endsWith(".json")) {
    return "application/json";
  }
  if (file.endsWith(".yaml") || file.endsWith(".yml")) {
    return "application/yaml";
  }
  if (file.endsWith(".md")) {
    return "text/markdown";
  }
  return "application/octet-stream";
}

async function generateSchemas() {
  const schemas = [];
  for (const definition of schemaDefinitions) {
    schemas.push({ ...definition, schema: await readJson(path.join(schemaRoot, definition.file)) });
  }

  // Each schema constant is typed as `JsonSchemaDocument` (a loose structural
  // type) rather than inferred via `as const`. `as const` would make every
  // nested property of the schema document part of the exported type, which
  // is what previously blew up dist/schemas.d.ts to ~750 KB: consumers only
  // need metadata and named $defs typed precisely, with subschemas as data.
  const lines = [generatedHeader("spec/schemas/*.schema.json"), 'import type { JsonObject, JsonSchemaDocument } from "../json.js";', ""];
  for (const { name, schema } of schemas) {
    const defsType = schema.$defs
      ? ` & { readonly $defs: { ${Object.keys(schema.$defs).map(key => `readonly ${JSON.stringify(key)}: JsonObject`).join("; ")} } }`
      : "";
    lines.push(`export const ${name}: JsonSchemaDocument${defsType} = ${asTs(schema)};`, "");
  }
  lines.push("export const schemas = {");
  for (const { name } of schemas) {
    lines.push(`  ${name},`);
  }
  lines.push("} as const;", "");
  lines.push(`export const schemaNames = ${asTs(schemas.map(({ name }) => name))} as const;`, "");
  lines.push("export type SchemaName = keyof typeof schemas;", "");

  lines.push("/** One entry per bundled schema: its name, spec-relative file path, and parsed document. */");
  lines.push("export interface SchemaEntry {");
  lines.push("  readonly name: SchemaName;");
  lines.push("  readonly file: string;");
  lines.push("  readonly schema: JsonSchemaDocument;");
  lines.push("}", "");
  lines.push("export const schemaEntries: readonly SchemaEntry[] = [");
  for (const { name, file } of schemas) {
    lines.push(`  { name: ${JSON.stringify(name)}, file: ${JSON.stringify(path.posix.join("schemas", file))}, schema: ${name} },`);
  }
  lines.push("];", "");

  await fs.writeFile(path.join(generatedRoot, "schemas.ts"), lines.join("\n"));
}

async function orderedCatalogFiles(definition, catalogDir, index) {
  const key = definition.indexRecordsKey ?? "records";
  const indexedFiles = Array.isArray(index[key])
    ? index[key].map((record) => record.file).filter(Boolean)
    : [];
  const allFiles = (await fs.readdir(catalogDir))
    .filter((file) => file.endsWith(".json") && file !== "index.json")
    .sort();
  const extras = allFiles.filter((file) => !indexedFiles.includes(file));
  return [...indexedFiles, ...extras];
}

async function generateCatalogs() {
  const catalogs = [];
  for (const definition of catalogDefinitions) {
    const catalogDir = path.join(catalogRoot, definition.dir);
    const index = await readJson(path.join(catalogDir, "index.json"));
    const files = await orderedCatalogFiles(definition, catalogDir, index);
    const records = [];
    for (const file of files) {
      records.push(await readJson(path.join(catalogDir, file)));
    }
    catalogs.push({ ...definition, index, records, files });
  }

  const schemaDefinitionByName = new Map(schemaDefinitions.map((definition) => [definition.name, definition]));
  const typeInfoByKind = new Map(catalogs.map(({ kind, schemaName }) => {
    const schemaDefinition = schemaDefinitionByName.get(schemaName);
    return [kind, {
      typeName: schemaDefinition.typeName,
      typeFile: schemaDefinition.typeFile ?? schemaDefinition.name,
    }];
  }));

  // Each catalog is typed as `readonly <Type>[]` (the same generated
  // interface used for the schema's own type) instead of being inferred via
  // `as const`. `as const` turned every record's every field into a literal
  // type, and — because the records were referenced again from `catalogs`
  // and `catalogEntries` below — that literal structure was duplicated three
  // times over in dist/catalogs.d.ts (~1.5 MB). Typing the source of truth
  // once, structurally, means every later reference reuses that same (tiny)
  // declared type instead of re-inferring the literal shape.
  const lines = [generatedHeader("spec/catalogs/<catalog-kind>/*.json")];
  for (const { kind } of catalogs) {
    const { typeName, typeFile } = typeInfoByKind.get(kind);
    lines.push(`import type { ${typeName} } from "./types/${typeFile}.js";`);
  }
  lines.push('import type { SchemaName } from "./schemas.js";', "");

  // Deliberately no index signature: some catalog record interfaces (e.g.
  // ChartType) come from schemas with `additionalProperties: false` and so
  // have no index signature of their own. Requiring one here would make
  // those types fail to structurally match `CatalogRecord`.
  lines.push("/** Structural shape shared by every bundled catalog record. */");
  lines.push("export interface CatalogRecord {");
  lines.push("  readonly id: string;");
  lines.push("}", "");

  lines.push("/** A lightweight summary entry inside a catalog's `index.json`. */");
  lines.push("export interface CatalogIndexRecord {");
  lines.push("  readonly id: string;");
  lines.push("  readonly name: string;");
  lines.push("  readonly file: string;");
  lines.push("  readonly [key: string]: unknown;");
  lines.push("}", "");

  lines.push("/** Parsed shape of a catalog's `index.json`. */");
  lines.push("export interface CatalogIndex {");
  lines.push("  readonly $schema: string;");
  lines.push("  readonly version: string;");
  lines.push("  readonly description: string;");
  lines.push("  readonly records: readonly CatalogIndexRecord[];");
  lines.push("  readonly [key: string]: unknown;");
  lines.push("}", "");

  for (const { kind, records } of catalogs) {
    const { typeName } = typeInfoByKind.get(kind);
    lines.push(`export const ${kind}: readonly ${typeName}[] = ${asTs(records)} as readonly ${typeName}[];`, "");
  }
  lines.push("export const catalogs = {");
  for (const { kind } of catalogs) {
    lines.push(`  ${kind},`);
  }
  lines.push("} as const;", "");
  lines.push("export type CatalogKind = keyof typeof catalogs;", "");
  lines.push("export const catalogIndexes: Record<CatalogKind, CatalogIndex> = {");
  for (const { kind, index } of catalogs) {
    lines.push(`  ${kind}: ${asTs(index)},`);
  }
  lines.push("};", "");
  lines.push("export const catalogSchemaNames: Record<CatalogKind, SchemaName> = {");
  for (const { kind, schemaName } of catalogs) {
    lines.push(`  ${kind}: ${JSON.stringify(schemaName)},`);
  }
  lines.push("};", "");
  lines.push(`export const catalogKinds = ${asTs(catalogs.map(({ kind }) => kind))} as const;`, "");

  lines.push("/** One entry per bundled catalog kind, with its records and index resolved. */");
  lines.push("export interface CatalogEntry {");
  lines.push("  readonly kind: CatalogKind;");
  lines.push("  readonly schemaName: SchemaName;");
  lines.push("  readonly dir: string;");
  lines.push("  readonly files: readonly string[];");
  lines.push("  readonly records: readonly CatalogRecord[];");
  lines.push("  readonly index: CatalogIndex;");
  lines.push("}", "");
  lines.push("export const catalogEntries: readonly CatalogEntry[] = [");
  for (const { kind, schemaName, dir, files } of catalogs) {
    const specDir = path.posix.join("catalogs", dir);
    lines.push(
      `  { kind: ${JSON.stringify(kind)}, schemaName: ${JSON.stringify(schemaName)}, dir: ${JSON.stringify(specDir)}, files: ${asTs(files)}, records: ${kind}, index: catalogIndexes.${kind} },`,
    );
  }
  lines.push("];", "");

  await fs.writeFile(path.join(generatedRoot, "catalogs.ts"), lines.join("\n"));
}

async function generateCatalogIds() {
  // Lightweight id-only view of the bundled catalogs so the validator can
  // check references without pulling full catalog records into its bundle.
  const lines = [generatedHeader("spec/catalogs/<catalog-kind>/*.json")];
  lines.push("export const catalogIds = {");
  for (const definition of catalogDefinitions) {
    const catalogDir = path.join(catalogRoot, definition.dir);
    const index = await readJson(path.join(catalogDir, "index.json"));
    const files = await orderedCatalogFiles(definition, catalogDir, index);
    const ids = [];
    for (const file of files) {
      const record = await readJson(path.join(catalogDir, file));
      if (typeof record.id === "string") {
        ids.push(record.id);
      }
    }
    lines.push(`  ${definition.kind}: ${asTs(ids)},`);
  }
  lines.push("} as const;", "");

  await fs.writeFile(path.join(generatedRoot, "catalog-ids.ts"), lines.join("\n"));
}

function asUnion(values) {
  return values.map((value) => `  | ${JSON.stringify(value)}`).join("\n");
}

async function generateSpecFiles() {
  const files = await collectFiles(specRoot);
  const entries = files.map((file) => ({
    path: file,
    packagePath: `@openpresentation/opf/spec/${file}`,
    kind: specFileKind(file),
    mediaType: mediaTypeForSpecFile(file),
  }));
  const kinds = [...new Set(entries.map((entry) => entry.kind))];

  // `SpecFilePath` and `SpecFileKind` are public literal unions, so they are
  // emitted directly as string-literal union types from the data. The entry
  // array itself is typed structurally (`readonly SpecFileEntry[]`) instead
  // of via `as const`: inferring a literal object type per spec file is what
  // previously re-serialized every entry into dist/spec-files.d.ts (~130 KB).
  const lines = [generatedHeader("spec/**/*")];
  lines.push("/** Path of a file under `spec/`, relative to the spec root. */");
  lines.push(`export type SpecFilePath =\n${asUnion(files)};`, "");
  lines.push("/** Category of a bundled spec file. */");
  lines.push(`export type SpecFileKind =\n${asUnion(kinds)};`, "");
  lines.push("/** One entry per file shipped under `@openpresentation/opf/spec/`. */");
  lines.push("export interface SpecFileEntry {");
  lines.push("  readonly path: SpecFilePath;");
  lines.push("  readonly packagePath: string;");
  lines.push("  readonly kind: SpecFileKind;");
  lines.push("  readonly mediaType: string;");
  lines.push("}", "");
  lines.push(`export const specFileEntries: readonly SpecFileEntry[] = ${asTs(entries)};`, "");
  lines.push(`export const specFilePaths: readonly SpecFilePath[] = ${asTs(files)};`, "");
  lines.push(`export const specFileKinds: readonly SpecFileKind[] = ${asTs(kinds)};`, "");

  await fs.writeFile(path.join(generatedRoot, "spec-files.ts"), lines.join("\n"));
}

async function generateTypes() {
  await fs.mkdir(generatedTypesRoot, { recursive: true });
  for (const definition of schemaDefinitions) {
    const schema = await readJson(path.join(schemaRoot, definition.file));
    const schemaForTypes = JSON.parse(JSON.stringify(schema));
    schemaForTypes.title = definition.typeName;
    const typeFile = definition.typeFile ?? definition.name;
    const source = await compile(schemaForTypes, definition.typeName, {
      bannerComment: generatedHeader(path.posix.join("schemas", definition.file)).trimEnd(),
      unreachableDefinitions: true,
      format: false,
      style: {
        semi: true,
        singleQuote: false,
        tabWidth: 2,
        trailingComma: "all",
      },
    });
    await fs.writeFile(path.join(generatedTypesRoot, `${typeFile}.ts`), source);
  }
}

await fs.rm(generatedRoot, { recursive: true, force: true });
await fs.mkdir(generatedRoot, { recursive: true });
await generateSchemas();
await generateCatalogs();
await generateCatalogIds();
await generateSpecFiles();
await generateTypes();
