import assert from 'node:assert/strict';
import {fitList,composeSlide} from '../dist/composition.js';
import {paginateSlide} from '../dist/pagination.js';
const box={x:15,y:20,width:300,height:800};
const options={style:{fontFamily:'Base',fontWeight:400,path:'slides.0.items'},textMeasurement:{measure:(text,size,style)=>Array.from(text).length*size*(style.fontWeight===700?.8:.5)}};
const items=['Plain entry',[{text:'Linked emphasis',bold:true,link:'https://example.org'}],{text:['Nested ',{text:'large',fontSize:24}],description:[{text:'Detailed explanation',italic:true}],level:4}];
const before=structuredClone(items),fit=fitList(items,box,20,20,options);
assert.equal(fit.listEntries.length,3);
assert.equal(fit.listEntries[0].textPath,'slides.0.items.0');
assert.equal(fit.listEntries[1].textPath,'slides.0.items.1');
assert.equal(fit.listEntries[2].descriptionPath,'slides.0.items.2.description');
assert.equal(fit.listEntries[2].textBox.x,box.x+20*1.1*5);
assert.ok(fit.listEntries[2].descriptionBox.y>fit.listEntries[2].textBox.y+fit.listEntries[2].text.height);
assert.equal(fit.listEntries[2].descriptionBox.x,fit.listEntries[2].textBox.x);
assert.equal(fit.listEntries[2].description.richLines[0].fragments[0].style.italic,true);
assert.equal(fit.listEntries[1].text.richLines[0].fragments[0].run.link,'https://example.org');
assert.equal(fit.listEntries[2].text.richLines.flatMap(l=>l.fragments).find(f=>f.run.fontSize).fontSize,32);
const wrapped=fitList([{text:'Words that need multiple lines for a hanging indent',level:1}],{...box,width:160},20,20,options).listEntries[0];
assert.ok(wrapped.text.lines.length>2);
assert.ok(wrapped.text.richLines.every(l=>l.fragments[0].x===0));
assert.equal(wrapped.text.lines.join(''),'Words that need multiple lines for a hanging indent');
const small=fitList(items,{...box,height:100},20,10,options);
assert.ok(small.fontSize<20&&!small.overflow);
assert.ok(small.listEntries.every(e=>e.text.fontSize===small.fontSize));
assert.equal(small.listEntries[2].description.fontSize,small.fontSize*.82);
assert.equal(small.listEntries[2].text.richLines.flatMap(l=>l.fragments).find(f=>f.run.fontSize).fontSize,32*small.fontSize/20);
assert.equal(fitList([{text:'Deep',level:100}],box,20,20,options).overflow,true);
assert.equal(fitList([],box,20,20,options).height,0);
assert.deepEqual(fitList([{text:'',description:''}],box,20,20,options).lines,['','']);
const unicode=fitList(['e\u0301👩‍💻'],{...box,width:24},20,20,options);
assert.deepEqual(unicode.lines,['e\u0301','👩‍💻']);assert.equal(unicode.overflow,true);
assert.deepEqual(items,before);
for(const value of [[{text:'Bad',level:-1}],[{text:'Bad',level:1.5}],[{text:123}]])assert.throws(()=>fitList(value,box));
const slide={type:'text',bullets:[{text:[{text:'Huge '.repeat(400),fontSize:60}],level:2}],composition:{overflow:'warn'}};
assert.ok(composeSlide(slide).items.find(i=>i.field==='bullets').text.listEntries);
assert.ok(composeSlide(slide).diagnostics.some(d=>d.code==='text-overflow'));
assert.throws(()=>composeSlide({...slide,composition:{overflow:'error'}}),{code:'layout-overflow'});
const long=Array.from({length:30},(_,i)=>({text:[{text:`Entry ${i}`,bold:true}],description:['Preserve ',{text:'every run',italic:true}],level:i%3}));
const paginated=paginateSlide({items:long});
assert.ok(paginated.slides.length>1);
assert.deepEqual(paginated.slides.flatMap(s=>s.items),long);
assert.ok(paginated.slides.every(s=>!composeSlide(s).diagnostics.length));
console.log('Lists passed: rich runs, descriptions, nesting, hanging indents, consistent shrink, source paths, Unicode, overflow and exact pagination.');
