import assert from 'node:assert/strict';
import {paginateSlide, OPFPaginationError} from '../dist/pagination.js';
import {composeSlide,wrapText} from '../dist/composition.js';
import {validatePresentation} from '../dist/index.js';
const original='Keep every word, space, and emoji 👨‍👩‍👧‍👦.\n'.repeat(100);
const slide={id:'source',title:'A long explanation',notes:'Notes belong to the original slide.',composition:{overflow:'error'},text:original};
const before=structuredClone(slide);
const result=paginateSlide(slide,{reservedIds:['source--2']});
assert.ok(result.slides.length>1);
assert.deepEqual(slide,before);
assert.equal(result.slides.map(page=>page.text).join(''),original);
assert.equal(result.slides[0].id,'source');assert.equal(result.slides[1].id,'source--3');
assert.equal(result.slides[1].notes,undefined);
assert.equal(validatePresentation({slides:result.slides}).valid,true);
for(const page of result.slides) assert.equal(composeSlide(page).diagnostics.length,0);
assert.deepEqual(result,paginateSlide(slide,{reservedIds:['source--2']}));
let offset=0;
for(const page of result.pages) {
 assert.equal(page.mappings[0].range.start,offset);offset=page.mappings[0].range.end;
}
assert.equal(offset,original.length);
const rich=[{text:original,bold:true,link:'https://example.com'},' final'];
const richResult=paginateSlide({text:rich});
assert.equal(richResult.slides.flatMap(s=>s.text).map(r=>typeof r==='string'?r:r.text).join(''),original+' final');
assert.ok(richResult.slides.flatMap(s=>s.text).filter(r=>typeof r==='object').every(r=>r.bold&&r.link==='https://example.com'));
const nested={title:'Nested',composition:{mode:'column'},blocks:[{composition:{mode:'column'},blocks:[{text:original},{text:'last'}]},{text:'outside'}]};
const nestedResult=paginateSlide(nested);
const nestedItems=nestedResult.slides.flatMap(s=>composeSlide(s).items.filter(i=>i.field==='text'));
assert.equal(nestedItems.map(i=>i.value).join(''),original+'lastoutside');
assert.ok(nestedResult.slides.some(s=>s.blocks[0].blocks));
for(const page of nestedResult.pages)for(const mapping of page.mappings)assert.ok(mapping.sourcePath.startsWith('slides.0.blocks.'));
const list=Array.from({length:80},(_,i)=>({text:`Point ${i}`,description:'Preserve item metadata.',level:0}));
const listResult=paginateSlide({items:list});assert.deepEqual(listResult.slides.flatMap(s=>s.items),list);
const table={columns:['Item','Value'],rows:Array.from({length:80},(_,i)=>[`Row ${i}`,i])};
const tableResult=paginateSlide({table});assert.ok(tableResult.slides.length>1);assert.deepEqual(tableResult.slides.flatMap(s=>s.table.rows),table.rows);
for(const s of tableResult.slides){assert.deepEqual(s.table.columns,table.columns);assert.equal(composeSlide(s).diagnostics.length,0);}
const region=paginateSlide({left:{text:original},right:{text:'Context'}});assert.equal(region.slides.map(s=>s.left?.text??'').join(''),original);
assert.equal(region.slides.filter(s=>s.right).length,1);
assert.throws(()=>paginateSlide(slide,{maxSlides:1}),OPFPaginationError);
assert.throws(()=>paginateSlide({title:original,text:'body'}),OPFPaginationError);
assert.throws(()=>paginateSlide({items:[original]}),OPFPaginationError);
assert.throws(()=>paginateSlide({text:'x'},{maxSlides:0}),RangeError);
assert.deepEqual(paginateSlide({text:'Already fits'}).slides,[{text:'Already fits'}]);
assert.deepEqual(wrapText('👨‍👩‍👧‍👦👨‍👩‍👧‍👦',10,16),['👨‍👩‍👧‍👦','👨‍👩‍👧‍👦']);
console.log('Pagination: exact text/rich-run preservation, groups, lists, tables, regions, mappings, IDs, limits and fit passed.');
const {paginatePresentation}=await import('../dist/pagination.js');
const deck={name:'Preserved metadata',assets:{},slides:[slide,{id:'source--2',text:'Final slide'}]};
const paginated=paginatePresentation(deck);
assert.equal(paginated.presentation.name,deck.name);
assert.equal(paginated.presentation.slides.at(-1).id,'source--2');
assert.equal(new Set(paginated.presentation.slides.map(s=>s.id)).size,paginated.presentation.slides.length);
assert.equal(paginated.pages.at(-1).sourceSlideIndex,1);
assert.ok(paginated.pages.at(-1).mappings[0].outputPath.startsWith(`slides.${paginated.presentation.slides.length-1}.`));
assert.throws(()=>paginatePresentation({slides:[{layout:'not-local',text:'x'}]}),OPFPaginationError);
for(const page of result.slides)assert.ok(composeSlide(page).items.find(item=>item.field==='text').text.fontSize>=24);
assert.throws(()=>paginateSlide({text:'x'},{minFontSize:0}),RangeError);
