import assert from 'node:assert/strict';
import {fitRichText,composeSlide} from '../dist/composition.js';
const box={x:0,y:0,width:240,height:200};
const measurement={measure:(text,size,style)=>Array.from(text).length*size*(style.fontWeight===700?.8:.5),resolveStyle:style=>style.fontFamily==='alias'?{...style,fontFamily:'Resolved'}:style};
const options={style:{fontFamily:'Base',fontWeight:400,path:'slides.0.text'},textMeasurement:measurement};
let checks=0;const check=(value,message)=>{assert.ok(value,message);checks++;};
const input=['Before ',{text:'BOLD',bold:true,fontFamily:'alias',color:'#ff0000'},' after'];
const fit=fitRichText(input,box,20,20,options);
check(fit.richLines.flatMap(line=>line.fragments).some(part=>part.style.fontFamily==='Resolved'&&part.style.fontWeight===700),'Run style resolution');
check(fit.richLines.flatMap(line=>line.fragments).map(p=>p.text).join('')==='Before BOLD after','Content preserved');
check(fit.richLines.every(line=>line.width<=box.width),'Wrapping');
const enlarged=fitRichText([{text:'Large large large',fontSize:36}],box,20,20,options);
check(enlarged.richLines.length>fit.richLines.length,'Point-sized runs affect wrapping');
check(enlarged.richLines[0].fragments[0].fontSize===48,'Point to pixel conversion');
check(fitRichText([{text:'Absolute points',fontSize:12}],{...box,width:1000},40,40,options).richLines[0].fragments[0].fontSize===16,'Explicit points stay absolute across canvas sizes');
const scripts=fitRichText(['H',{text:'2',subscript:true},'O and x',{text:'2',superscript:true}],box,20,20,options);
check(scripts.richLines.flatMap(l=>l.fragments).some(f=>f.baselineShift>0),'Subscript');
check(scripts.richLines.flatMap(l=>l.fragments).some(f=>f.baselineShift<0),'Superscript');
const whitespace=fitRichText([' A  B\n\nC\r\n'],{...box,width:1000},20,20,options);
assert.deepEqual(whitespace.lines,[' A  B','','C','']);checks++;
const unicode=fitRichText(['e\u0301👩‍💻e\u0301'],{...box,width:2},20,20,options);
check(unicode.lines.every(line=>['e\u0301','👩‍💻'].includes(line)),'Never split graphemes');
check(unicode.overflow,'Too-wide grapheme diagnoses overflow');
const noMutation=JSON.stringify(input);fitRichText(input,box);check(JSON.stringify(input)===noMutation,'No mutation');
assert.throws(()=>fitRichText([{text:'bad',fontSize:0}],box),/positive/);checks++;
const boldRows=composeSlide({composition:{mode:'row'},blocks:[{text:[{text:'Big '.repeat(300),fontSize:80}]}]},{width:500,height:300,textMeasurement:measurement});
check(boldRows.items[0].text.richLines.length>0,'Composition stores mixed-style geometry');
check(boldRows.diagnostics.some(d=>d.code==='text-overflow'),'Composition reports actual mixed-style overflow');
console.log(`Rich text passed ${checks} shared-layout checks.`);
