import assert from 'node:assert/strict';
import test from 'node:test';
import {mkdtemp,readFile,writeFile,mkdir,rm,symlink,realpath,readdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {spawnSync} from 'node:child_process';
const require=createRequire(import.meta.url);
const {build}=createRequire(require.resolve('tsup'))('esbuild');
const cli=fileURLToPath(new URL('../dist/index.js',import.meta.url));
const bundle={'opf-author':{'SKILL.md':'# Author\n','references/old.md':'Previous guidance\n'},'opf-inspect':{'SKILL.md':'# Inspect\n'}};
async function fixture(run){
  const root=await mkdtemp(path.join(tmpdir(),'opf-skills-test-'));
  try{
    const module=path.join(root,'skills.mjs');
    await build({entryPoints:[fileURLToPath(new URL('../src/skills.ts',import.meta.url))],outfile:module,bundle:true,platform:'node',format:'esm',target:'node20'});
    await run(root,await import(pathToFileURL(module).href));
  }finally{
    const actual=await realpath(root),parent=await realpath(tmpdir());
    assert.ok(actual.startsWith(parent+path.sep)&&path.basename(actual).startsWith('opf-skills-test-'));
    await rm(actual,{recursive:true,force:true});
  }
}
test('managed skills install, idempotence, safe update and recoverable previous files',()=>fixture(async(root,{manageSkills})=>{
  const directory=path.join(root,'project/.agents/skills'),options={directory};
  await mkdir(path.join(root,'project'),{recursive:true});
  await writeFile(path.join(root,'project/AGENTS.md'),'Existing project instructions');
  const first=await manageSkills('install',bundle,'1.0.0',options);
  assert.deepEqual(first.changed,['opf-author','opf-inspect']);
  assert.equal(await readFile(path.join(directory,'opf-author/references/old.md'),'utf8'),'Previous guidance\n');
  assert.deepEqual((await manageSkills('install',bundle,'1.0.0',options)).changed,[]);
  const next={...bundle,'opf-author':{'SKILL.md':'# Updated author\n','references/new.md':'New guidance\n'}};
  await writeFile(path.join(directory,'opf-inspect/SKILL.md'),'Local customization');
  await assert.rejects(manageSkills('update',next,'2.0.0',options),/No skills changed/);
  assert.equal(await readFile(path.join(directory,'opf-author/SKILL.md'),'utf8'),'# Author\n','Preflight covers every skill before writes');
  assert.equal((await manageSkills('status',next,'2.0.0',options)).skills.find(item=>item.name==='opf-inspect').status,'modified');
  await writeFile(path.join(directory,'opf-inspect/SKILL.md'),bundle['opf-inspect']['SKILL.md']);
  await writeFile(path.join(directory,'opf-author/custom.md'),'Preserve this extra file');
  await assert.rejects(manageSkills('update',next,'2.0.0',options),/No skills changed/);
  await rm(path.join(directory,'opf-author/custom.md'));
  await writeFile(path.join(directory,'opf-author/__proto__'),'Preserve unusual extra file names too');
  await assert.rejects(manageSkills('update',next,'2.0.0',options),/No skills changed/);
  await rm(path.join(directory,'opf-author/__proto__'));
  const updated=await manageSkills('update',next,'2.0.0',options);
  assert.equal(await readFile(path.join(directory,'opf-author/SKILL.md'),'utf8'),'# Updated author\n');
  await assert.rejects(readFile(path.join(directory,'opf-author/references/old.md')),error=>error.code==='ENOENT');
  const backup=updated.backups.find(item=>item.endsWith('opf-author.previous'));
  assert.ok(!backup.startsWith(directory+path.sep),'Backups stay outside agent skill discovery');
  assert.equal(await readFile(path.join(backup,'references/old.md'),'utf8'),'Previous guidance\n');
  assert.equal(await readFile(path.join(root,'project/AGENTS.md'),'utf8'),'Existing project instructions');
  assert.ok((await readdir(directory)).every(name=>name.startsWith('opf-')),'Successful installs remove the transaction lock');
}));
test('unmanaged destinations, links and another installer lock are preserved',()=>fixture(async(root,{manageSkills,skillDestination})=>{
  const directory=path.join(root,'skills'),outside=path.join(root,'outside');
  await mkdir(path.join(directory,'opf-author'),{recursive:true});
  await writeFile(path.join(directory,'opf-author/SKILL.md'),'User owned');
  await assert.rejects(manageSkills('install',bundle,'1.0.0',{directory}),/unmanaged/);
  assert.equal(await readFile(path.join(directory,'opf-author/SKILL.md'),'utf8'),'User owned');
  await writeFile(path.join(directory,'opf-author/.opf-managed.json'),'null');
  assert.equal((await manageSkills('status',bundle,'1.0.0',{directory})).skills[0].status,'unmanaged');
  await assert.rejects(manageSkills('update',bundle,'1.0.0',{directory}),/unmanaged/);
  assert.equal(skillDestination({agent:'codex'},root),path.join(root,'.agents/skills'));
  assert.equal(skillDestination({agent:'codex',global:true},root,root),path.join(root,'.codex/skills'));
  assert.equal(skillDestination({agent:'claude-code'},root),path.join(root,'.claude/skills'));
  assert.equal(skillDestination({agent:'cursor'},root),path.join(root,'.cursor/skills'));
  assert.throws(()=>skillDestination({agent:'toString'},root),/Supported agents/);
  assert.throws(()=>skillDestination({directory,global:true},root),/cannot be combined/);
  await mkdir(outside);
  await writeFile(path.join(outside,'sentinel.txt'),'Untouched');
  const link=path.join(root,'linked-skills');
  await symlink(outside,link,process.platform==='win32'?'junction':'dir');
  await assert.rejects(manageSkills('install',bundle,'1.0.0',{directory:link}),/symlink/);
  assert.deepEqual(await readdir(outside),['sentinel.txt']);
  const project=path.join(root,'real-project'),alias=path.join(root,'linked-project');
  await mkdir(project);
  await symlink(project,alias,process.platform==='win32'?'junction':'dir');
  const viaAlias={directory:path.join(alias,'.agents/skills')};
  const linkedInstall=await manageSkills('install',bundle,'1.0.0',viaAlias);
  assert.equal(linkedInstall.directory,path.join(await realpath(project),'.agents/skills'));
  assert.equal(await readFile(path.join(project,'.agents/skills/opf-author/SKILL.md'),'utf8'),'# Author\n');
  assert.equal((await manageSkills('status',bundle,'1.0.0',viaAlias)).skills[0].status,'managed');
  assert.deepEqual((await manageSkills('update',bundle,'1.0.0',viaAlias)).changed,[]);
  const locked=path.join(root,'locked');await mkdir(locked);await writeFile(path.join(locked,'.opf-install.lock'),'Other installation');
  await assert.rejects(manageSkills('install',bundle,'1.0.0',{directory:locked}),/Another skill installation/);
  assert.equal(await readFile(path.join(locked,'.opf-install.lock'),'utf8'),'Other installation');
}));
test('CLI bundles all six complete skills and advertises the actual npx command',()=>fixture(async(root)=>{
  const destination=path.join(root,'actual-skills');
  const run=args=>spawnSync(process.execPath,[cli,...args],{cwd:root,encoding:'utf8'});
  const installed=run(['skills','install','--directory',destination]);
  assert.equal(installed.status,0,installed.stderr);
  assert.equal(JSON.parse(installed.stdout).changed.length,6);
  assert.match(await readFile(path.join(destination,'opf-inspect/scripts/opf-inspect.mjs'),'utf8'),/validatePresentation/);
  assert.ok(JSON.parse(await readFile(path.join(destination,'opf-author/assets/decision-brief.opf.json'),'utf8')).slides.length>0);
  assert.equal(JSON.parse(run(['skills','status','--directory',destination]).stdout).skills.length,6);
  assert.equal(run(['skills','unknown']).status,2);
  assert.equal(run(['skills','install','--agent','unknown']).status,2);
  assert.match(run(['--help']).stdout,/npx @openpresentation\/cli@latest skills install/);
  const created=run(['create','deck.opf.json']);assert.equal(created.status,0,created.stderr);
  assert.equal(JSON.parse(created.stdout).agentSkills,'npx @openpresentation/cli@latest skills install');
}));
