#!/usr/bin/env node
// Builds @openpresentation/gallery's dist/ from the catalog records in catalog/ and the layout previews in
// previews/layouts/ (RR-78). The package has no runtime dependency: the records are inlined into dist/index.js and the
// previews into dist/previews.js, and the declarations in src/ are copied next to them.
//
//   node scripts/build.mjs
//
// catalog/ is written by the monorepo's scripts/sync-gallery-catalog.mjs from a pptx.gallery checkout; never edit it by
// hand. The shape of `gallery` is the shape core resolves (`Catalog`): `source` and the eight content kinds, each record
// keyed by id without `$schema`, `id` or `x-*` members.
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogRoot = path.join(packageRoot, "catalog");
const previewsRoot = path.join(packageRoot, "previews", "layouts");
const dist = path.join(packageRoot, "dist");

export const GALLERY_SOURCE = "https://www.pptx.gallery";

/** The content kinds a document references, in core's `catalogKinds` order, with their catalog/ directory. */
export const CONTENT_KINDS = [
  ["layouts", "layouts"],
  ["themes", "themes"],
  ["colorSchemes", "color-schemes"],
  ["fontSchemes", "font-schemes"],
  ["narratives", "narratives"],
  ["audiences", "audiences"],
  ["purposes", "purposes"],
  ["tones", "tones"],
];
/** The display kinds: picker metadata for engine vocabularies, never referenced by a document. */
export const DISPLAY_KINDS = [
  ["chartTypes", "chart-types"],
  ["languages", "languages"],
  ["socialPlatforms", "social-platforms"],
];

const readJson = async (file) => JSON.parse(await readFile(file, "utf8"));

/** The record a document embeds: no `$schema`, no `id` (the key is the id), no publisher `x-*` members. */
export function embeddedCopy(record) {
  return Object.fromEntries(Object.entries(record).filter(([key]) => key !== "$schema" && key !== "id" && !key.startsWith("x-")));
}

/** Reads catalog/<dir>/index.json and its records in index order. */
export async function readKind(root, dir) {
  const index = await readJson(path.join(root, dir, "index.json"));
  const records = [];
  for (const entry of index.records) records.push(await readJson(path.join(root, dir, entry.file)));
  return { index, records };
}

/** Everything dist/index.js exports, as plain data. */
export async function readCatalog(root = catalogRoot) {
  const keyed = (records) => Object.fromEntries(records.map((record) => [record.id, embeddedCopy(record)]));
  const gallery = { source: GALLERY_SOURCE };
  const display = {};
  const indexes = {};
  for (const [key, dir] of CONTENT_KINDS) {
    const { index, records } = await readKind(root, dir);
    gallery[key] = keyed(records);
    indexes[key] = index;
  }
  for (const [key, dir] of DISPLAY_KINDS) {
    const { index, records } = await readKind(root, dir);
    display[key] = keyed(records);
    indexes[key] = index;
  }
  const manifest = await readJson(path.join(root, "manifest.json"));
  return { gallery, display, indexes, manifest };
}

const literal = (value) => `JSON.parse(${JSON.stringify(JSON.stringify(value))})`;

export async function build() {
  const pkg = await readJson(path.join(packageRoot, "package.json"));
  const catalogSchema = pkg.opf?.catalogSchema;
  if (!Number.isInteger(catalogSchema)) throw new Error("package.json opf.catalogSchema must be an integer");
  const { gallery, display, indexes, manifest } = await readCatalog();
  if (manifest.publisher !== GALLERY_SOURCE) throw new Error(`catalog/manifest.json publisher is ${manifest.publisher}, expected ${GALLERY_SOURCE}`);

  const index = `// Generated by scripts/build.mjs from catalog/. Do not edit by hand.
const data = ${literal({ gallery, display, indexes, manifest })};
// Frozen to the depth core's former defaultCatalog was: the catalog, each kind and each record. A record's nested values
// are not, so an engine that reads them behaves exactly as with that object.
const freeze = (value, depth) => {
  if (depth > 0 && value && typeof value === "object") {
    for (const child of Object.values(value)) freeze(child, depth - 1);
    Object.freeze(value);
  }
  return value;
};
/** The source the gallery is registered under, and the \`source\` of a document's \`catalogs.default\`. */
export const GALLERY_SOURCE = ${JSON.stringify(GALLERY_SOURCE)};
/** The version of core's catalog record schemas these records target (package.json \`opf.catalogSchema\`). */
export const CATALOG_SCHEMA = ${catalogSchema};
/** The pptx.gallery catalog: register it with \`catalogs: [gallery]\`. */
export const gallery = freeze(data.gallery, 3);
/** Display metadata for pickers: chart types, languages and social platforms by id. */
export const catalogDisplay = freeze(data.display, 3);
/** Each kind's \`index.json\`: the record summaries and their content hash. */
export const catalogIndexes = freeze(data.indexes, 1);
/** The pptx.gallery commit these records were synced from, and a content hash per kind. */
export const catalogManifest = freeze(data.manifest, 1);
`;

  const previewIndex = await readJson(path.join(previewsRoot, "index.json"));
  const previews = {};
  for (const record of previewIndex.records) {
    // The renderer ends each file with a newline; the string keeps the fragment only.
    previews[record.id] = (await readFile(path.join(previewsRoot, record.file), "utf8")).replace(/\n$/, "");
  }
  const previewsJs = `// Generated by scripts/build.mjs from previews/layouts/. Do not edit by hand.
const data = ${literal({ previews, index: previewIndex })};
/** Static HTML for each layout preview slug: a self-contained Tailwind-styled fragment that fills a 16:9 thumbnail. */
export const layoutPreviews = Object.freeze(data.previews);
/** The preview index: the slugs, their files and byte counts. */
export const layoutPreviewIndex = Object.freeze(data.index);
/** Slugs of every layout that ships an HTML preview, sorted. */
export const layoutPreviewSlugs = Object.freeze(Object.keys(data.previews).sort());
/** Whether an HTML preview exists for the slug. */
export function hasLayoutPreview(slug) {
  return Object.hasOwn(data.previews, slug);
}
/** The HTML preview for a slug, or undefined when none ships. */
export function getLayoutPreview(slug) {
  return Object.hasOwn(data.previews, slug) ? data.previews[slug] : undefined;
}
`;

  // Only files whose bytes change are written, and only stale ones removed, so a build that runs beside another (the
  // CI job builds once and its parallel steps call `build` again) never leaves dist/ empty or half written.
  const files = {
    "index.js": index,
    "previews.js": previewsJs,
    "index.d.ts": await readFile(path.join(packageRoot, "src", "index.d.ts"), "utf8"),
    "previews.d.ts": await readFile(path.join(packageRoot, "src", "previews.d.ts"), "utf8"),
  };
  await mkdir(dist, { recursive: true });
  for (const name of await readdir(dist)) if (!(name in files) && !name.endsWith(".tmp")) await rm(path.join(dist, name), { recursive: true, force: true });
  for (const [name, text] of Object.entries(files)) {
    const target = path.join(dist, name);
    if (existsSync(target) && (await readFile(target, "utf8")) === text) continue;
    const temporary = `${target}.${process.pid}.tmp`;
    await writeFile(temporary, text);
    await rename(temporary, target);
  }
  const count = Object.values(gallery).reduce((sum, records) => sum + (typeof records === "object" ? Object.keys(records).length : 0), 0);
  return { records: count, previews: previewIndex.records.length };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { records, previews } = await build();
  process.stdout.write(`Built @openpresentation/gallery: ${records} content records, ${previews} layout previews.\n`);
}
